services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'customerdb'
      MYSQL_USER: 'customeruser'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '54321'
    ports:
      - '3306:3306'
